name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as svg"
author: "platane"

runs:
  using: node20
  main: dist/index.js

inputs:
 github_user_name: Beatriz-Oliveira-Dev
   description: "github user name"
   required: true
github_token:
  description: "github token used to fetch the contribution calendar. Default to the action token if empty."
  required: false
  default: ${{ github.token }}
outputs:
    required: false
